name: Go
on:
  push:
    paths:
      - greeting/**
      - .github/workflows/greeting.yml

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: pushd greeting && go build && popd

    - name: Test
      id: test
      run: |
        go get -u github.com/jstemmer/go-junit-report
        export PATH=$PATH:~/go/bin
        pushd greeting
        go test -covermode=count -coverprofile=profile.out . -v | tee test.out
        go tool cover -html=profile.out -o coverage.html
        cat test.out | go-junit-report > junit.xml
        popd
    - name: check on failures
      if: steps.test.outputs.status != 0
      run: exit 1

    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        go get -u github.com/kisielk/errcheck
        export PATH=$PATH:~/go/bin
        mkdir lint
        pushd greeting
        golint . 2>&1 | tee ../lint/lint.txt
        errcheck -blank . 2>&1 | tee ../lint/errcheck.txt
        if $? != 0 ; then
          exit 1
        fi
        popd
