name: Go
on:
  push:
    paths:
      - greeting/**
      - .github/workflows/greeting.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: pushd greeting && go build && popd

      - name: Test
        run: |
          mkdir -p publish
          pushd greeting
          go test -covermode=count -coverprofile=profile.out . -v; result=$?; echo $result | tee result.out
          test $result -eq 0
          go tool cover -html=profile.out -o ../publish/coverage.html
          popd

      - name: Lint
        run: |
          mkdir -p publish
          go get -u golang.org/x/lint/golint
          go get -u github.com/kisielk/errcheck
          export PATH=$PATH:~/go/bin
          pushd greeting
          golint . 2>&1 | tee ../publish/lint.txt
          errcheck -blank . 2>&1 | tee ../publish/errcheck.txt
          popd

      - name: Upload reports
        uses: actions/upload-artifact@v1
        with:
          name: build-reports
          path: publish

      - name: Deploy reports to pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
